name: Makefile CI - Build, run, push container

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed for checkout
      packages: read # Grants permission to pull packages from ghcr.io
    container:
      image: ghcr.io/jordanblakey/gh_actions_runner:latest
      options: --user root

    steps:
      - name: check github context
        run: |
          echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
          echo "GITHUB_REPOSITORY: ${{ github.repository }}"
          echo "GITHUB_ACTOR: ${{ github.actor }}"

      - uses: actions/checkout@v4

      - name: install dependencies
        run: apk add make nodejs

      - name: docker build
        run: make build

      - name: docker run
        run: make run

      - name: docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker push
        run: make push
