name: Makefile CI - Build, run, push container

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: docker build
      run: make build

    - name: docker run
      run: make run

    - name: docker push
      run: make push
