name: Makefile CI - Build, run, push container

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-in-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed for checkout
      packages: read # Grants permission to pull packages from ghcr.io
    container:
      image: ghcr.io/jordanblakey/gh_actions_runner:latest
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: apk add make nodejs
      - name: docker build
        run: make build

  rest-of-steps:
    runs-on: ubuntu-latest
    needs: build-in-container
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4
      - name: docker run
        run: make run
      - name: docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker push
        run: make push
