name: Makefile CI - Build, run, push container

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jordanblakey/gh_actions_runner:latest
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: make build
      - name: Run the Docker container
        run: make run
      - name: Check github context
        run: |
          echo "github.actor: ${{ github.actor }}"
          echo "github.repository: ${{ secrets.GITHUB_TOKEN }}"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker push
        run: make push
