name: Makefile CI - Build, run, push container

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read # Allows checkout
    #   packages: write # Grants permission to push packages

    steps:
      - name: login to GitHub CLI
        run: "gh auth login --with-token < ${{ secrets.GITHUB_TOKEN }}"

      - name: inspect permissions
        run: |
          echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
          echo "GITHUB_REPOSITORY: ${{ github.repository }}"
          echo "GITHUB_ACTOR: ${{ github.actor }}"
          gh auth status

      - uses: actions/checkout@v4

      - name: docker build
        run: make build

      - name: docker run
        run: make run

      - name: docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker push
        run: make push
